//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop_2.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Workshop_2.View.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat Length: .
        /// </summary>
        internal static string addBoatLength {
            get {
                return ResourceManager.GetString("addBoatLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new boat where added!.
        /// </summary>
        internal static string addBoatSuccess {
            get {
                return ResourceManager.GetString("addBoatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat type: .
        /// </summary>
        internal static string addBoatType {
            get {
                return ResourceManager.GetString("addBoatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members name: .
        /// </summary>
        internal static string addMemberName {
            get {
                return ResourceManager.GetString("addMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members social security number: .
        /// </summary>
        internal static string addMemberSSN {
            get {
                return ResourceManager.GetString("addMemberSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new member where added!.
        /// </summary>
        internal static string addMemberSuccess {
            get {
                return ResourceManager.GetString("addMemberSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to return to menu..
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string backKey {
            get {
                return ResourceManager.GetString("backKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canoe.
        /// </summary>
        internal static string boatTypeCanoe {
            get {
                return ResourceManager.GetString("boatTypeCanoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorsailer.
        /// </summary>
        internal static string boatTypeMotorsailer {
            get {
                return ResourceManager.GetString("boatTypeMotorsailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string boatTypeOther {
            get {
                return ResourceManager.GetString("boatTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sailboat.
        /// </summary>
        internal static string boatTypeSailbot {
            get {
                return ResourceManager.GetString("boatTypeSailbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose boat to edit: .
        /// </summary>
        internal static string chooseBoatToEdit {
            get {
                return ResourceManager.GetString("chooseBoatToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a boat number to remove.
        /// </summary>
        internal static string chooseBoatToRemove {
            get {
                return ResourceManager.GetString("chooseBoatToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of all members with name, member id and number of boat/boats.
        /// </summary>
        internal static string compactListOfMembers {
            get {
                return ResourceManager.GetString("compactListOfMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------.
        /// </summary>
        internal static string divider {
            get {
                return ResourceManager.GetString("divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit boat.
        /// </summary>
        internal static string editBoat {
            get {
                return ResourceManager.GetString("editBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The boat where updated!.
        /// </summary>
        internal static string editBoatSuccess {
            get {
                return ResourceManager.GetString("editBoatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit member.
        /// </summary>
        internal static string editMember {
            get {
                return ResourceManager.GetString("editMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member where updated with the new information!.
        /// </summary>
        internal static string editMemberSuccess {
            get {
                return ResourceManager.GetString("editMemberSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again..
        /// </summary>
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter members ID: .
        /// </summary>
        internal static string getMemberId {
            get {
                return ResourceManager.GetString("getMemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member do not exist, try again: .
        /// </summary>
        internal static string getMemberIDFail {
            get {
                return ResourceManager.GetString("getMemberIDFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member has no boats registered.
        /// </summary>
        internal static string memberHasNoBoat {
            get {
                return ResourceManager.GetString("memberHasNoBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a boat to an existing user.
        /// </summary>
        internal static string menuAddNewBoat {
            get {
                return ResourceManager.GetString("menuAddNewBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new member.
        /// </summary>
        internal static string menuAddNewMember {
            get {
                return ResourceManager.GetString("menuAddNewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to quit....
        /// </summary>
        internal static string menuGoodBye {
            get {
                return ResourceManager.GetString("menuGoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your choice: .
        /// </summary>
        internal static string menuMakeChoice {
            get {
                return ResourceManager.GetString("menuMakeChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string menuQuit {
            get {
                return ResourceManager.GetString("menuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show compact list of members.
        /// </summary>
        internal static string menuShowCompactListOfMembers {
            get {
                return ResourceManager.GetString("menuShowCompactListOfMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show verbose list of members.
        /// </summary>
        internal static string menuShowVerboseListOfMembers {
            get {
                return ResourceManager.GetString("menuShowVerboseListOfMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to this amazing application!.
        /// </summary>
        internal static string menuWelcome {
            get {
                return ResourceManager.GetString("menuWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again: .
        /// </summary>
        internal static string menuWrongChoice {
            get {
                return ResourceManager.GetString("menuWrongChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}m.
        /// </summary>
        internal static string presentBoat {
            get {
                return ResourceManager.GetString("presentBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat {0}, {1}, {2}m.
        /// </summary>
        internal static string presentBoatInformation {
            get {
                return ResourceManager.GetString("presentBoatInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has ID {1} and has {2} boat(s).
        /// </summary>
        internal static string presentCompactList {
            get {
                return ResourceManager.GetString("presentCompactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members name: {0}.
        /// </summary>
        internal static string presentMembersName {
            get {
                return ResourceManager.GetString("presentMembersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member have {0} boat(s).
        /// </summary>
        internal static string presentMembersNumberOfBoats {
            get {
                return ResourceManager.GetString("presentMembersNumberOfBoats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members social security number: {0}.
        /// </summary>
        internal static string presentMembersSSN {
            get {
                return ResourceManager.GetString("presentMembersSSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has Id {1} and has boat/boats..
        /// </summary>
        internal static string presentShortMember {
            get {
                return ResourceManager.GetString("presentShortMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}, Social Security Number: {1}, Member ID: {2}.
        /// </summary>
        internal static string presentVerboseList {
            get {
                return ResourceManager.GetString("presentVerboseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a boat from member.
        /// </summary>
        internal static string removeBoat {
            get {
                return ResourceManager.GetString("removeBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string removeBoatSuccess {
            get {
                return ResourceManager.GetString("removeBoatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a member.
        /// </summary>
        internal static string removeMember {
            get {
                return ResourceManager.GetString("removeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user were removed successfully.
        /// </summary>
        internal static string removeMemberSuccess {
            get {
                return ResourceManager.GetString("removeMemberSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIST OF MEMBERS AND BOATS.
        /// </summary>
        internal static string verboseListOfMembers {
            get {
                return ResourceManager.GetString("verboseListOfMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be a whole number, try again: .
        /// </summary>
        internal static string wrongLength {
            get {
                return ResourceManager.GetString("wrongLength", resourceCulture);
            }
        }
    }
}
